services:
  postgres:
    image: postgres
    container_name: postgres_expense_tracker
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Senhasql123
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
